name: Bitboxer
title: Bitboxer - hacking
url: https://bitboxer.de

timezone: Europe/Berlin

paginate: 9
paginate_path: "/page/:num"

permalink: /:year/:month/:day/:title/
emoji_dir: /assets/images/emoji

exclude: ["deploy.sh", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "theme", "Makefile", "config.ru"]

plugins: ["jekyll-paginate", "jekyll-sitemap"]
