name: Bitboxer
title: Bitboxer - hacking
disqus_short_name: bitboxercodingblog
url: http://bitboxer.de

markdown: redcarpet
highlighter: pygments
timezone: Europe/Berlin

paginate: 30
paginate_path: "/page/:num"

permalink: /:year/:month/:day/:title/
emoji_dir: /css/emoji
